// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: enum.proto

package echoproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CommandType int32

const (
	CommandType__CommandNone CommandType = 0
	CommandType_CreateRoom   CommandType = 1
	CommandType_CloseRoom    CommandType = 2
	CommandType_EnterRoom    CommandType = 3
	CommandType_LeaveRoom    CommandType = 4
	CommandType_SendMessage  CommandType = 5
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "_CommandNone",
		1: "CreateRoom",
		2: "CloseRoom",
		3: "EnterRoom",
		4: "LeaveRoom",
		5: "SendMessage",
	}
	CommandType_value = map[string]int32{
		"_CommandNone": 0,
		"CreateRoom":   1,
		"CloseRoom":    2,
		"EnterRoom":    3,
		"LeaveRoom":    4,
		"SendMessage":  5,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType__MessageNone MessageType = 0
	MessageType_Text         MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "_MessageNone",
		1: "Text",
	}
	MessageType_value = map[string]int32{
		"_MessageNone": 0,
		"Text":         1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{1}
}

type RespStatus int32

const (
	RespStatus__StatusNone     RespStatus = 0
	RespStatus_OK              RespStatus = 1
	RespStatus_NotAllow        RespStatus = 2
	RespStatus_NotAuth         RespStatus = 3
	RespStatus_ErrNotFound     RespStatus = 4
	RespStatus_ErrBusy         RespStatus = 5
	RespStatus_ErrUnKnown      RespStatus = 6
	RespStatus_ErrInputInvalid RespStatus = 7
)

// Enum value maps for RespStatus.
var (
	RespStatus_name = map[int32]string{
		0: "_StatusNone",
		1: "OK",
		2: "NotAllow",
		3: "NotAuth",
		4: "ErrNotFound",
		5: "ErrBusy",
		6: "ErrUnKnown",
		7: "ErrInputInvalid",
	}
	RespStatus_value = map[string]int32{
		"_StatusNone":     0,
		"OK":              1,
		"NotAllow":        2,
		"NotAuth":         3,
		"ErrNotFound":     4,
		"ErrBusy":         5,
		"ErrUnKnown":      6,
		"ErrInputInvalid": 7,
	}
)

func (x RespStatus) Enum() *RespStatus {
	p := new(RespStatus)
	*p = x
	return p
}

func (x RespStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[2].Descriptor()
}

func (RespStatus) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[2]
}

func (x RespStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespStatus.Descriptor instead.
func (RespStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{2}
}

var File_enum_proto protoreflect.FileDescriptor

var file_enum_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x6d, 0x0a, 0x0b,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x5f,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x01, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x05, 0x2a, 0x29, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x5f, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x54, 0x65, 0x78, 0x74, 0x10, 0x01, 0x2a, 0x83, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x70, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x4e, 0x6f, 0x74, 0x41, 0x75, 0x74, 0x68, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x72, 0x72,
	0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x72,
	0x72, 0x42, 0x75, 0x73, 0x79, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x72, 0x72, 0x55, 0x6e,
	0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x06, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x72, 0x72, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x07, 0x42, 0x2f, 0x5a, 0x2d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x68, 0x61, 0x6c, 0x65,
	0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2f, 0x77, 0x68, 0x61, 0x6c, 0x65, 0x45, 0x63, 0x68, 0x6f, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x65, 0x63, 0x68, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enum_proto_rawDescOnce sync.Once
	file_enum_proto_rawDescData = file_enum_proto_rawDesc
)

func file_enum_proto_rawDescGZIP() []byte {
	file_enum_proto_rawDescOnce.Do(func() {
		file_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_proto_rawDescData)
	})
	return file_enum_proto_rawDescData
}

var file_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_enum_proto_goTypes = []interface{}{
	(CommandType)(0), // 0: CommandType
	(MessageType)(0), // 1: MessageType
	(RespStatus)(0),  // 2: RespStatus
}
var file_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_proto_init() }
func file_enum_proto_init() {
	if File_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_proto_goTypes,
		DependencyIndexes: file_enum_proto_depIdxs,
		EnumInfos:         file_enum_proto_enumTypes,
	}.Build()
	File_enum_proto = out.File
	file_enum_proto_rawDesc = nil
	file_enum_proto_goTypes = nil
	file_enum_proto_depIdxs = nil
}
