version: '3'
services:
  whaleEcho:
    image: "whaleteam/whaleecho:latest"
    ports:
    - "10033:10033"
    volumes:
    - ../../configs:/whaleEcho/configs
    networks:
    - echonet
    environment: 
    - ENV=docker_dev
    depends_on: 
    - nats
    - redis
    environment: 
    - CONFIG_NAME=app-container
  nats:
    image: "nats-streaming:0.18.0-alpine3.12"
    volumes: 
    - natsstream:/nats/db
    command: ["-cid", "whale", "-DV", "--store", "FILE", "--dir", "/nats/db"]
    networks:
    - echonet
  redis:
    image: redis:6.0.6-alpine
    volumes:
    - redisdb:/data
    networks:
    - echonet


networks:
  echonet:
volumes:
  natsstream:
  redisdb: