log:
  local: true
  level: debug
  app_id: whale-echo
  env: dev
stan:
  addr: nats:4222
  reconn_wait: 1
  reconn_delay: 600
  pool_size: 20
  conn_timeout: 3
  cluster_id: whale
ws_server:
  addr: 127.0.0.1
  port: 10033
redis:
  addr: "redis:6379"
  db: 0