log:
  local: true
  level: debug
  app_id: whale-echo
  env: test
stan:
  addr: 127.0.0.1:4222
  reconn_wait: 1
  reconn_delay: 600
  cluster_id: whale
redis:
  addr: "127.0.0.1:6379"
  db: 0
ws_server:
  addr: 127.0.0.1
  port: 10033